server.name=UserApplication
server.port=8081

db.type=mongodb

mongodb.uri=mongodb://localhost:27017
mongodb.database=springmimic

#log.level=INFO
logging.level=DEBUG
logging.output=file   # or 'console' or 'both'
logging.file=logs/custom.log

static.path=public
