server.name=UserApplication
server.port=8081

#db.type=mongodb
db.type=h2
#db.type=mysql           # or "mongodb"

database.url=jdbc:mysql://localhost:3306/sakila
database.username=root
database.password=Basement99!

h2.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
h2.username=sa
h2.password=password

mongodb.uri=mongodb://localhost:27017
mongodb.database=springmimic

#log.level=INFO
logging.level=DEBUG
logging.output=file   # or 'console' or 'both'
logging.file=logs/custom.log

static.path=public
